### PR TITLE
add test structure and coverage tests

### PR DESCRIPTION
**Pull request by Jonathansoufer**
This PR implements basic Jest Tests ensuring rendering screens.

### CODE REVIEW

**Review by obernardovieira — CHANGES_REQUESTED** [review]
1. CI is failing
2. `coverage` folder was commited

**Comment by Jonathansoufer** [comment]
Both fixed!

**Review by obernardovieira — COMMENTED** [review]
"Force Jest Installation" it's a bit strong. I would prefer "Install Jest Locally".
But I'm wondering, why don't we install dev dependencies?

**Comment by Jonathansoufer** [comment]
Should I change the message for the sake of history?

About the hack, I didn't manage to find out the reason circleCI wasn't
installing the packages correctly after researching for a while ...

**Comment by obernardovieira** [comment]
you were just missing one tiny detail

**Review by obernardovieira — APPROVED** [review]

**Pull request merged**
