### PR TITLE
[IPCT1-295] - Add sagas to initial & more stories

### PR DESCRIPTION
**Pull request by Jonathansoufer**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (fixes an issue)
- [ ] New feature (adds functionality)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Hardware:
* SDK:

# Screenshots/Videos
Please add any screenshots that can be helpful in case there was some UI improvents. Screenshots from multiple devices are a must.

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Jonathansoufer** [comment]
IMG_1403
IMG_1402
IMG_1401

**Review by obernardovieira — CHANGES_REQUESTED** [review]
1. I can only see one community
2. "encountered two children with the same key" - this shows too many times
3. opening a story is such a bad experience. It wasn't like that. I think it's caused by 2.  (https://drive.google.com/file/d/1OP56IXA7qSxvKbsx_nLZwE1ZVfNFSHuI/view?usp=sharing)

Screenshot_20210720-171106
Screenshot_20210720-170746

**Review by obernardovieira — CHANGES_REQUESTED** [review]
conflicts

**Comment by Jonathansoufer** [comment]
Fixed

**Review by obernardovieira — APPROVED** [review]

**Pull request merged**
