### PR TITLE
Fix/ipct1 360/fix copy contract bug

### PR DESCRIPTION
**Pull request by Jonathansoufer**
This PR fixes [IPCT1-360] at https://impactmarket.atlassian.net/browse/IPCT1-360

# Description
This PR fix an open bug in expo clipboard which we noticed on donate button but could happen in all clipboard usage. 

### Type of change

- Bug fix (fixes an issue)

# How Has This Been Tested?

- [x] Manually
  - [x] [BLU Advance L5](https://www.amazon.com/Advance-A390L-Unlocked-Phone-Camera/dp/B07Z6Q9NCZ/)
  - [ ] [SLIDE SP4514](https://www.amazon.com/dp/B06ZZ4KZF9?psc=1&ref=ppx_yo2_dt_b_product_details)
  - [ ] [Asus ZenFone 3 Max](https://www.gsmarena.com/asus_zenfone_3_max_zc520tl-8207.php)
  - [] [iPhone 6](https://www.gsmarena.com/apple_iphone_6-6378.php)
  - [x] [iPhone 11](https://www.gsmarena.com/apple_iphone_11-9848.php)
  - [x] Other [XIAOMI REDMI 5 Plus] (https://www.gsmarena.com/xiaomi_redmi_5_plus_(redmi_note_5)-8959.php)
- [ ] Automated

# Screenshots/Videos

https://user-images.githubusercontent.com/44679989/128504722-d1366fbe-7c4b-4d04-88a3-79e946ab094c.MP4

### CODE REVIEW

**Comment by obernardovieira** [comment]
but... why did expo-clipboard didn't work? :thinking:

**Comment by obernardovieira** [comment]
Well... the mentioned error is for react-native-clipboard, not expo-clipboard, related to expo sdk38, not sdk42, from almost a year ago. It was working not long ago, doesn't seem very reasonable :thinking:

**Comment by Jonathansoufer** [comment]
Did you checked the comments and it’s dates!? It’s bug which means can
happen in some circumstances. I did research for a while, but if doesn’t
seem reasonable to you we will need to check another approach.

**Comment by Jonathansoufer** [comment]
I added back the expo library following the import format from docs and re-installed the pkg.

**Review by obernardovieira — APPROVED** [review]

**Comment by obernardovieira** [comment]
non used component `ModalValoraTimeoutError` is for future usage.

**Pull request merged**
