### PR TITLE
Feat/ipct1 371/update input UI

### PR DESCRIPTION
**Pull request by Jonathansoufer**
This PR fixes [IPCT1-367] at https://impactmarket.atlassian.net/browse/IPCT1-367

# Description
This PR add a lock icon on locked inputs in order to give visual feedback to users.

### Type of change
- New feature (adds functionality)

# How Has This Been Tested?

- [x] Manually
  - [ ] [BLU Advance L5](https://www.amazon.com/Advance-A390L-Unlocked-Phone-Camera/dp/B07Z6Q9NCZ/)
  - [ ] [SLIDE SP4514](https://www.amazon.com/dp/B06ZZ4KZF9?psc=1&ref=ppx_yo2_dt_b_product_details)
  - [ ] [Asus ZenFone 3 Max](https://www.gsmarena.com/asus_zenfone_3_max_zc520tl-8207.php)
  - [ ] [iPhone 6](https://www.gsmarena.com/apple_iphone_6-6378.php)
  - [x] Other [REDMI 5Plus](https://www.gsmarena.com/xiaomi_redmi_5_plus_(redmi_note_5)-8959.php)
- [ ] Automated

# Screenshots/Videos

IMG_B77FDF2064E0-1

### CODE REVIEW

**Review by obernardovieira — CHANGES_REQUESTED** [review]
1. It doesn't match the design (wrong order and the message above inputs is missing)
2. instead of a `locked` parameter, let's think of something more generic and add a `right` option, so that we can send anything, and for example, use on "create community" inputs
3. a clean commit timeline, please

**Comment by Jonathansoufer** [comment]
1) UI refactored to include missing text 
2) added rightIcon prop to make it reusable

**Review by obernardovieira — CHANGES_REQUESTED** [review]
Not `rightIcon`, just `right`. We might want to put some text there, like in "create community".
The commit history is still very messy.

**Comment by Jonathansoufer** [comment]
We cannot use right as a prop since this will produce the following error below. Instead I used rightElement which reflect more what this prop is about it.

IMG_1553

**Comment by obernardovieira** [comment]
Pushed to master with cherry-pick. Available from https://github.com/impactMarket/mobile-app/commit/493136c4b0fb6dee6969a7e334bab6edb93e9eb8 to https://github.com/impactMarket/mobile-app/commit/76891ec3175bd94f6851454e89c24db770c4b93f
Reason: maintain a clean git history.

**Pull request closed without merging**
